name: "🐞 Bug Report"
description: "Report a bug or unexpected behavior in Notion CMS Automation Guide"
title: "[BUG] - "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "### 🐛 Thank you for reporting a bug! Please fill out the details below."

  - type: textarea
    id: what-happened
    attributes:
      label: "📌 Describe the Bug"
      description: "What went wrong? Provide a detailed description."
      placeholder: "I encountered an error when..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "🔄 Steps to Reproduce"
      description: "Provide a step-by-step guide to replicate the issue."
      placeholder: |
        1. Run `notion_api_script.py`
        2. Use the following API request...
        3. Observe the error message...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "✅ Expected Behavior"
      description: "What should have happened instead?"
      placeholder: "The script should have returned the correct database entries..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "🛠 Error Logs or Screenshots"
      description: "Paste any relevant error logs, screenshots, or terminal output."
      placeholder: "Traceback (most recent call last)..."
      render: shell

  - type: input
    id: environment
    attributes:
      label: "💻 System Info"
      description: "What system are you using?"
      placeholder: "OS: Windows 11, Python 3.9, Notion API v1.0"

  - type: checkboxes
    id: checklist
    attributes:
      label: "📝 Checklist"
      description: "Before submitting, make sure you've done the following:"
      options:
        - label: "I have searched [existing issues](https://github.com/yourgithubusername/Notion-CMS-Automation-Guide/issues) to ensure this is not a duplicate."
          required: true
        - label: "I have checked the [Notion API documentation](https://developers.notion.com/)."
        - label: "I have tried debugging the issue with `print()` or logging."