blank_issues_enabled: false
contact_links:
  - name: 📖 Read the Contribution Guide
    url: https://github.com/yourgithubusername/Notion-CMS-Automation-Guide/blob/main/CONTRIBUTING.md
    about: Please review the contribution guidelines before submitting an issue.
  - name: 🗣 Ask a Question in Discussions
    url: https://github.com/yourgithubusername/Notion-CMS-Automation-Guide/discussions
    about: For general questions, use GitHub Discussions instead of opening an issue.